name = "stiamond"
main = ".open-next/worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next"
not_found_handling = "none"
html_handling = "none"
